// let age = 21;
// console.log(age);

// const name = "chandan raj";
// let city = "gurugram";
// // const name = 'chandan raj';
// city = "delhi";
// console.log(city);
// console.log(name);

// if (5>2) {
//     var output = "true";
// }
// console.log(output);
// let x = 5;
// console.log(x);

// car = {
//     brand : "honda",
//     model : "hyundai",
//     year : 2025
// }
// let  = "red";
// console.log(car);

// let x = 5;
// let y = 5;
// console.log(x+y);
// console.log(x-y);
// console.log(x*y);
// console.log(x/y);
// console.log(x%  y);

// let x =5;
// let y = "5";
// console.log(x==y);
// console.log(x===y);

// let marks =[54,66,72,]
// let sumOfmarks =0;
// for (idx=0; idx<marks.length; idx++) {
//     sumOfmarks =sumOfmarks+marks[idx];
// }
// let avg = sumOfmarks/marks.length;
// console.log(avg);

// let prices =[54,66,72];
// for (let i=0; i<prices.length; i++ ) {
//     let offer = prices[i]/10;
//     prices[i] =prices[i]-offer;
// }
// console.log(prices);

// sum of all array elements

// let marks =[1,2,3,4,5];
// let sum =0;
// for (idx of marks) {
//     let mark = idx;
//     sum += mark;
// }
// console.log(`sum of marks = ${sum}`);

// // find the largest number in the array

// const arr = [3,1,7,2,9,4];
// let lnum = 0;
// for (val of arr) {
//     if (arr[val]> lnum) {
//         lnum =arr[val];
//     }
// }
// console.log(lnum);

// filter even number
// let arr = [1,2,3,4,5,6,7,8,9];

// let newArr = [];
// for (let i=0; i<arr.length; i++) {
//     if(arr[i]%2 === 0) {
//         newArr.push(arr[i]);
//     }
// }
// console.log(newArr);

// double all values

// const arr = [1,2,3,4];
// let newArr = [];
// for (let i=0; i<arr.length; i++) {
//     newArr.unshift(arr[i]*2);
// }
// console.log(newArr);

// const arr =['bloomberg', 'microsoft', 'uber', 'google','ibm'];
// // add amazon at the end
// // arr.push('amazon');

// arr.splice(2,1,'ola');

// functions in javascript

// function sum(name) {
//     console.log(`my name is ${name}`);
// }
// sum('chandan');
// sum("rakesh");

// arrow functions

// const myArrowFunction = () => {
//     console.log('chandan raj');
// }

// console.log(myArrowFunction)

